### ISSUE TITLE
Printer pausing between objects.  Nozzle cools down then warms back up, causing PETG issues

### ISSUE THREAD

**Issue by cmdlinebeep** [thwerks/GCode-Auto-Arranger#1]
Pretty much what the title says.  I couldn't detect these issues when using the Gcode previewer in PrusaSlicer (though maybe there is a way to see nozzle temp, etc.) but basically it is cooling down and sitting there a minute or so between objects.  

I'm using PETG, so in this time I get quite a big filament blob/drip that messes up the next object (especially for smaller objects).  I'm printing a skirt on each object which helps, but it's still an issue.  Is it avoidable?

And thanks for making this awesome repo.  😊

**Comment by cmdlinebeep** [comment]
On the first object I see this Gcode (default from PrusaSlicer start code):

```
M140 S70 ; set final bed temp
M104 S150 ; set temporary nozzle temp to prevent oozing during homing
G4 S10 ; allow partial nozzle warmup
G28 ; home all axis
G1 Z50 F240
G1 X2 Y10 F3000
M104 S250 ; set final nozzle temp
M190 S70 ; wait for bed temp to stabilize
M109 S250 ; wait for nozzle temp to stabilize
```

But then between prints it uses:

```
M140 S70 ; set final bed temp
M104 S150 ; set temporary nozzle temp to prevent oozing during homing
M190 S70 ; wait for bed temp to stabilize
M109 S250 ; wait for nozzle temp to stabilize
```

So it is smart enough to recognize not to home all the axis each time, or to prime the nozzle each time.  Can it also know not to lower / mess with the temperatures between prints?  If it moves on quickly, with the retract that I think it's including, it shouldn't ooze.

I've attached the before and after .gcode files too in case that's helpful.  Had to change extension to .txt for the .gcode files to upload!

[1X_filament_dragon_clip.gcode.txt](https://github.com/thwerks/GCode-Auto-Arranger/files/10905232/1X_filament_dragon_clip.gcode.txt)
[12X_filament_dragon_clip (full bed).gcode.txt](https://github.com/thwerks/GCode-Auto-Arranger/files/10905233/12X_filament_dragon_clip.full.bed.gcode.txt)

**Comment by thwerks** [comment]
Normally slicers let you set a first layer temp setting for the hotend and bed that is different than subsequent layers. By default the auto arranger reproduces this; that being the first layer temp is set, then waits to reach that temp, then proceeds with the next part. 

Since someone may not want the default behavior I've just now added a variable to choose where or not to set the first layer temp again for each part and or whether the print should hold/wait for setting to be reached.  Please see latest update on Gitbub.

    printerReheat = true,           // set hotend and bed first layer temps
    printerReheatWait = false;      // force wait for first layer temps to be reached

**Comment by cmdlinebeep** [comment]
Sounds good, but wouldn't these variables always be used together?  Or do you really need all four combinations of these two variables?  I'd think if you want to Reheat, then you also want to Wait..

**Comment by thwerks** [comment]
It probably depends on how far apart the temps are and how critical the difference is. If they're not too far apart its probably sufficient to just set the temp and proceed with the print but in some cases that might not be sufficient. Ill just leave it to the end user to decide whats best.

Thank you for opening this case, correcting these issues makes this program more usable for others.

**Comment by cmdlinebeep** [comment]
Thanks for fixing this, I confirmed it working, but finally getting around to commenting.  😀
