### ISSUE TITLE
Purge issue between objects

### ISSUE THREAD

**Issue by cmdlinebeep** [thwerks/GCode-Auto-Arranger#2]
Starting a new issue since this is not related to the one we're discussing now...

I noticed also between objects, it's dumping a giant blob of filament purged out on the bed, then proceeding with the print.  This blob is often messing up the prints.  Trying to track that down, and I think it's related to this code:

```
                    buf += "\nG1 E-" + partRetraction + " F" + partRetractionSpeed;
                    buf += "\nM83";
                    if (sys.partVertical == true) {
                        buf += "\nG1 X" + String((Number(partStart.x) + Number(addX)).toFixed(3));
                        buf += "\nG1 Y" + String((Number(partStart.y) + Number(addY)).toFixed(3));
                    } else {
                        buf += "\nG1 Y" + String((Number(partStart.y) + Number(addY)).toFixed(3));
                        buf += "\nG1 X" + String((Number(partStart.x) + Number(addX)).toFixed(3));
                    }
                    buf += "\n" + gcode[0].tempBed;
                    buf += "\n" + gcode[0].tempExtruder;
                    buf += "\n" + gcode[0].tempBedWait;
                    buf += "\n" + gcode[0].tempExtruderWait;
                    buf += "\nM300 S1000 P200";
                    buf += "\nG1 E12 F" + partRetractionSpeed;
```

I believe the last line of this code is supposed to "undo" the retraction done in the first line of this code.  But it looks to me to be a bug, and no matter how much you set your filament retraction between parts, it's extruding 12mm of filament out in a giant blob.  

Shouldn't this last line be:

`buf += "\nG1 E" + partRetraction + " F" + partRetractionSpeed;`

?   

Thanks.

**Comment by thwerks** [comment]
****please be advised that the _partRetractionSpeed_ variable has changed to MM/Sec rather than MM/Min. please update your config as necessary .

**Comment by cmdlinebeep** [comment]
Thanks, this is perfect, I'd still like a little extra purge as you noted, just not so much.
